### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [maxstarkov/DevProFinalTask#13]
В комментарии к этому issue напишите ваши:
- Имя Фамилию (в дательном падеже)
- Адрес электронной почты, на которую выслать сертификат

**Comment by maxstarkov** [comment]
Максиму Старкову
maximstarkov@gmail.com

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by maxstarkov** [comment]
Подтверждаю! Большое спасибо!
